export default [
  {
    id: 16,
    extension: 'image',
    name: 'sahand-babali-gavODTHG36Y-unsplash.jpg',
    path: 'files/dad144bb1802fa43f4cdb5dacd8ff27f.jpg',
    size: '2.11 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 31,
    extension: 'image',
    name: 'evergreen-cms.png',
    path: 'files/evergreen-cms.png',
    size: '0.66 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 30,
    extension: 'image',
    name: 'visual-drag-drop-editing.png',
    path: 'files/visual-drag-drop-editing.png',
    size: '0.66 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 29,
    extension: 'image',
    name: 'media-library.png',
    path: 'files/media-library.png',
    size: '0.66 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 28,
    extension: 'image',
    name: 'custom-design.png',
    path: 'files/custom-design.png',
    size: '0.66 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 27,
    extension: 'image',
    name: 'blueprints-for-pages.png',
    path: 'files/blueprints-for-pages.png',
    size: '0.66 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 26,
    extension: 'image',
    name: 'ales-nesetril-Im7lZjxeLhg-unsplash.jpg',
    path: 'files/82195627cfc22bd2b2cf3710c3ec8bda.jpg',
    size: '0.66 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 25,
    extension: 'image',
    name: 'alesia-kazantceva-XLm6-fPwK5Q-unsplash.jpg',
    path: 'files/ce7d5fb2cb97435410902044d96855c5.jpg',
    size: '1.51 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 24,
    extension: 'image',
    name: 'andrew-mcelroy-3_PaUEEcwMc-unsplash.jpg',
    path: 'files/16689d296d315de351ceb6e83dd2b93b.jpg',
    size: '3.04 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 23,
    extension: 'image',
    name: 'austin-distel-wawEfYdpkag-unsplash.jpg',
    path: 'files/59188719aa3784760bed3cced63bd216.jpg',
    size: '6.08 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 22,
    extension: 'image',
    name: 'chris-ried-bN5XdU-bap4-unsplash.jpg',
    path: 'files/58fe2a745b33acebdb33f90fb8777a51.jpg',
    size: '2.84 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 21,
    extension: 'image',
    name: 'christin-hume-Hcfwew744z4-unsplash.jpg',
    path: 'files/da0e88fcdd2a181c3fa71fb24d895a80.jpg',
    size: '1.97 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 20,
    extension: 'image',
    name: 'clarisse-croset--tikpxRBcsA-unsplash.jpg',
    path: 'files/29c45b70252212d7bca14ec8da368dfb.jpg',
    size: '7.02 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 19,
    extension: 'image',
    name: 'fakurian-design-DgtbXKO1UOY-unsplash.jpg',
    path: 'files/58beec25d75ab4f0190247472dd07dd5.jpg',
    size: '0.57 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 18,
    extension: 'image',
    name: 'luke-chesser-JpY2rPHFL8E-unsplash.jpg',
    path: 'files/408dcc28519c41e2f926ba41822c86e5.jpg',
    size: '1.89 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 17,
    extension: 'image',
    name: 'nasa-cIX5TlQ_FgM-unsplash.jpg',
    path: 'files/6689921281927008bd747a13a29bd2da.jpg',
    size: '7.67 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 1,
    extension: 'image',
    name: 'jorge-ramirez-988-7dFbNlo-unsplash.jpg',
    path: 'files/fda5adba21b49f939754d6db5eb1961a.jpg',
    size: '2.08 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 15,
    extension: 'image',
    name: 'thisisengineering-raeng-GckgQqyHoa4-unsplash.jpg',
    path: 'files/d79e8ce7cf57fc4c0c7a69bb0780bbc8.jpg',
    size: '1.97 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 14,
    extension: 'image',
    name: 'thisisengineering-raeng-lfIDAUla2Hw-unsplash.jpg',
    path: 'files/76441caa3a136257bfd3fd408d4e09b1.jpg',
    size: '12.05 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 13,
    extension: 'image',
    name: 'thisisengineering-raeng-KQXrDYrfvnw-unsplash.jpg',
    path: 'files/0217ef4c816164f7a6bd7734cc3ad213.jpg',
    size: '2.01 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 12,
    extension: 'image',
    name: 'umberto-jXd2FSvcRr8-unsplash.jpg',
    path: 'files/923f95a94f60fc6916c39f5a7c919752.jpg',
    size: '5.21 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 11,
    extension: 'image',
    name: 'thisisengineering-raeng-sbFmoKBK7jU-unsplash.jpg',
    path: 'files/1cd9f6c0d0966a8086978a85fb6a0a7e.jpg',
    size: '0.87 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 10,
    extension: 'image',
    name: 'james-yarema-npTT9rD8wd4-unsplash.jpg',
    path: 'files/835e5fe093d27ccbd17ce560c45c123b.jpg',
    size: '1.75 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 9,
    extension: 'image',
    name: 'zq-lee-R6ZB8A9LAyg-unsplash.jpg',
    path: 'files/16d1a0383b12cf6a8489f946e673e45c.jpg',
    size: '2.36 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 8,
    extension: 'image',
    name: 'thisisengineering-raeng-ovWUKV1btXk-unsplash.jpg',
    path: 'files/1c31a080733e401489f1ec8d1f06fb27.jpg',
    size: '2.17 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 7,
    extension: 'image',
    name: 'remy-gieling-51IHV_v5iRs-unsplash.jpg',
    path: 'files/7ad98ddacea4aff50bfddf8544076d82.jpg',
    size: '1.69 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 6,
    extension: 'image',
    name: 'foto-sushi-6anudmpILw4-unsplash.jpg',
    path: 'files/15875d68711a32e5a86322dd9d734ca0.jpg',
    size: '1.14 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 5,
    extension: 'image',
    name: 'jenny-ueberberg-v_1k3vRX4kg-unsplash.jpg',
    path: 'files/bfe5858459d9d184522565b648c2fc85.jpg',
    size: '1.62 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 4,
    extension: 'image',
    name: 'ryan-hoffman-v7Jja2ChN6s-unsplash.jpg',
    path: 'files/5d2bbf472ee9c3529fa17b69f435b4a3.jpg',
    size: '2.28 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 3,
    extension: 'image',
    name: 'good-faces-yWTUg04EZU8-unsplash.jpg',
    path: 'files/0af6d8c297630b89ff66d494f01f43b4.jpg',
    size: '1.32 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  },
  {
    id: 2,
    extension: 'image',
    name: 'joshua-rawson-harris-VYTE_h_wx9g-unsplash.jpg',
    path: 'files/a9232ca8105bb67d216d138f0e0169a4.jpg',
    size: '6.75 MB',
    alt: 'The image alt',
    description: 'The image description',
    caption: 'The image caption',
  }
]